indentation error

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -40,40 +40,43 @@ jobs:
         id: init
         run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}"
 
-      - name: "Terraform Format"
-        id: fmt
-        run: terraform fmt -check
+      - name: Terraform Destroy
+        run: terraform destroy -auto-approve -input=false
 
-      - name: "Terraform Validate"
-        id: validate
-        run: terraform validate
+      # - name: "Terraform Format"
+      #   id: fmt
+      #   run: terraform fmt -check
 
-      - name: "Terraform Plan"
-        id: plan
-        run: terraform plan -no-color -input=false -out planfile
-        continue-on-error: true
+      # - name: "Terraform Validate"
+      #   id: validate
+      #   run: terraform validate
 
-      - name: "Terraform plan status"
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: "Terraform Plan"
+      #   id: plan
+      #   run: terraform plan -no-color -input=false -out planfile
+      #   continue-on-error: true
 
-      - name: "Terraform Apply"
-        id: apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+      # - name: "Terraform plan status"
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
+      # - name: "Terraform Apply"
+      #   id: apply
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      #   run: terraform apply -auto-approve -input=false -parallelism=1 planfile
 
-      - name: Get kube config file
-        id: eks
-        if: steps.apply.outcome == 'success'
-        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
+      # - name: Configure AWS credentials
+      #   uses: aws-actions/configure-aws-credentials@v2
+      #   with:
+      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      #     aws-region: ${{ env.AWS_REGION }}
 
-      - name: Install Ingress Controller
-        if: steps.apply.outcome == 'success' && steps.eks.outcome == 'success'
-        run: kubectl apply --validate=false -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.2/deploy/static/provider/aws/deploy.yaml
+      # - name: Get kube config file
+      #   id: eks
+      #   if: steps.apply.outcome == 'success'
+      #   run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
+
+      # - name: Install Ingress Controller
+      #   if: steps.apply.outcome == 'success' && steps.eks.outcome == 'success'
+      #   run: kubectl apply --validate=false -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.2/deploy/static/provider/aws/deploy.yaml
